In [1]:
%load_ext autoreload
%autoreload 
%reload_ext autoreload

In [2]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
from features import topological_features, aggregate_features, get_vars, extract_features
import pickle
import rolx
import numpy as np
import utils
import random

def get_scores(train_pred, train_true, test_pred, test_true):
    train_accuracy = np.mean(train_pred == train_true)
    print train_accuracy

    train_f1 =  precision_recall_fscore_support(train_true, train_pred)
    print train_f1[0][1]
    print train_f1[1][1]
    print train_f1[2][1]
    
    test_accuracy = np.mean(test_pred == test_true)
    print test_accuracy
    
    test_f1 =  precision_recall_fscore_support(test_true, test_pred)
    print test_f1[0][1]
    print test_f1[1][1]
    print test_f1[2][1]


In [3]:
def get_rolx(fname, fname_extended, roles=3):
    G, dict_to_graph, graph_to_dict = rolx.load_graph_igraph(fname, fname_extended)
    H, R = rolx.extract_rolx_roles(G, roles)
    print(H.shape, R.shape)
    H.tolist()

    adj_mat = G.get_adjacency()
    _, video_dict_list, graph_to_dict, neighbors, fields = get_vars(fname, fname_extended)
    # np.save('rolx_features', H)
    # H = np.load('rolx_features.npy')
    
    return adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields

def get_features(adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields, agg_flag=False):
    X = []
    y = []
    pos_data = []
    neg_data = []
    for row in range(adj_mat.shape[0]):
        H_row = np.array(H[row]).flatten()
        for col in range(adj_mat.shape[1]):
            H_total = np.array(H[col][0]).flatten() + H_row
            # print 'pre concatenated', type(H_total), H_total

            # flag for adding into agg and topo features
            if agg_flag:
                local_features = extract_features(video_dict_list, graph_to_dict, neighbors, fields, row, col) 
                # skip if doesnt exist
                if not local_features:
                    continue

                H_total = np.concatenate([H_total, local_features]) 
                # print 'after concatenated', type(H_total), H_total

            if adj_mat[row][col] > 0:
                pos_data.append((H_total, adj_mat[row][col]))
            else:
                neg_data.append((H_total, adj_mat[row][col]))
    
    return pos_data, neg_data

In [ ]:
fname = './dataset/0222/0.txt'
fname_extended = './dataset/0222/1.txt'

adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields = get_rolx(fname, fname_extended)
pos_data, neg_data = get_features(adj_mat, H, video_dict_list, graph_to_dict, neighbors, fields)

Creating Vertex Features matrix


rolx.py:95: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x_star, residuals, rank, s = lstsq(A, w)


V is a 3356 by 485 matrix.
Node-role matrix is of dimensions 3356 by 3
[[0.00126998 0.23255645 0.0053801 ]
 [0.         0.23278286 0.00700886]
 [0.         0.23278286 0.00700886]
 ...
 [0.         0.01115651 0.02619573]
 [0.         0.01115651 0.02619573]
 [0.         0.01244527 0.02430484]]
[[4.52246136e+04 1.42941075e-03 2.10000000e+01 ... 3.28100190e-04
  3.28100190e-04 2.10000000e+01]
 [1.63742690e-01 1.42797251e-03 2.00000000e+01 ... 3.07114183e-04
  3.07114183e-04 2.00000000e+01]
 [1.63742690e-01 1.42797251e-03 2.00000000e+01 ... 3.07114183e-04
  3.07114183e-04 2.00000000e+01]
 ...
 [0.00000000e+00 2.99759763e-04 4.00000000e+00 ... 1.75086647e-04
  1.75086647e-04 4.00000000e+00]
 [0.00000000e+00 2.99759763e-04 4.00000000e+00 ... 1.75086647e-04
  1.75086647e-04 4.00000000e+00]
 [0.00000000e+00 2.99759790e-04 5.00000000e+00 ... 2.10005872e-04
  2.10005872e-04 5.00000000e+00]]
[[0.00407925 0.         0.01161068 0.         0.         0.
  0.         0.01161172]
 [0.00833944 0.0513434

In [ ]:
fname_test = './dataset/080327/0.txt'
fname_test_extended = './dataset/080327/1.txt'

adj_mat_test, H_test, video_dict_list_test, graph_to_dict_test, neighbors_test, fields_test = get_rolx(fname_test, fname_test_extended)
pos_data_test, neg_data_test = get_features(adj_mat_test, H_test, video_dict_list_test, graph_to_dict_test, neighbors_test, fields_test)

In [87]:
def split_data_balanced(pos_data, neg_data):
    # creates positive and negative dataset for more uniform distribution of data
    X = [pos_data[i][0] for i in range(len(pos_data))]
    Y = [pos_data[i][1] for i in range(len(pos_data))]

    random_indices = sorted(random.sample(range(len(neg_data)), len(X)))
    X_neg = [neg_data[i][0] for i in random_indices]
    Y_neg = [neg_data[i][1] for i in random_indices]

    X.extend(X_neg)
    Y.extend(Y_neg)

    X_array = np.array(X)
    Y_array = np.array(Y)
    
    print X_array.shape, Y_array.shape
    from sklearn.preprocessing import normalize
    # change this line to change the number of features
    X_array = X_array[:, np.r_[:3]]
    print X_array.shape

    # runs training by splitting train/test sets
    return train_test_split(X_array, Y_array, test_size=0.2, random_state=42)

In [75]:
def split_data(pos_data, neg_data):
    # runs training by splitting train/test sets
    X = [pos_data[i][0] for i in range(len(pos_data))]
    Y = [pos_data[i][1] for i in range(len(pos_data))]

    X_neg = [neg_data[i][0] for i in range(len(neg_data))]
    Y_neg = [neg_data[i][1] for i in range(len(neg_data))]

    X.extend(X_neg)
    Y.extend(Y_neg)

    X_array = np.array(X)
    Y_array = np.array(Y)
    X_array = X_array[:, np.r_[:3]]

    X_train, X_test, y_train, y_test = train_test_split(X_array, Y_array, test_size=0.01, random_state=42)

    test_zero_vals = np.argwhere(y_test == 0)
    test_one_vals = np.argwhere(y_test == 1)
    print 'test zero vals', len(test_zero_vals), 'test one vals', len(test_one_vals)

    # zero_vals = np.argwhere(y_train == 0)
    one_vals = np.argwhere(y_train == 1)
    random_indices = zero_vals[sorted(random.sample(range(len(zero_vals)), len(one_vals)))]
    random_indices = np.concatenate([random_indices, one_vals]).reshape(-1)

    X_train = X_train[random_indices]
    y_train = y_train[random_indices]
    print X_train.shape, y_train.shape

    train_zero_vals = np.argwhere(y_train == 0)
    train_one_vals = np.argwhere(y_train == 1)
    print 'train zero vals', len(train_zero_vals), 'train one vals', len(train_one_vals)
    return X_train, X_test, y_train, y_test

In [109]:
X_train, _, y_train, _ = split_data_balanced(pos_data, neg_data)
_, X_test, _, y_test = split_data(pos_data_test, neg_data_test)

(140070,) (140070,)


IndexError: too many indices for array

In [60]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, max_depth=2,
                              random_state=0)
clf.fit(X_train, y_train)

print 'random forest'
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

get_scores(train_predictions, y_train, test_predictions, y_test)
np.savetxt('dataset/results.txt', test_predictions)

random forest
0.7310653580301577
0.7945686600395121
0.6232750350527636
0.6985746188414987
0.8369415710436569
0.014655172413793103
0.6100478468899522
0.028622741048378045


In [66]:
clf = LogisticRegression(random_state=0, solver='lbfgs').fit(X_train, y_train)
print 'logistic regression'
# makes predictions
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

get_scores(train_predictions, y_train, test_predictions, y_test)
np.savetxt('dataset/results.txt', test_predictions)

logistic regression
0.5
0.5
1.0
0.6666666666666666
0.003937972226932715
0.003937972226932715
1.0
0.007845050861454149


In [62]:
from sklearn import svm

svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)

print 'svm_rbf'
# makes predictions
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_preds, y_train, test_preds, y_test)
# np.savetxt('dataset/results.txt', test_predictions)

svm_rbf
0.5
0.5
1.0
0.6666666666666666
0.003937972226932715
0.003937972226932715
1.0
0.007845050861454149


In [63]:
from sklearn import svm

svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

print 'svm linear'
# makes predictions
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_preds, y_train, test_preds, y_test)
# np.savetxt('dataset/results.txt', test_predictions)

svm linear
0.5
0.5
1.0
0.6666666666666666
0.003937972226932715
0.003937972226932715
1.0
0.007845050861454149


In [64]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

print 'knn'
# makes predictions
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_preds, y_train, test_preds, y_test)

knn


/home/justinxu/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:268: DeprecationWarning: check_pickle is deprecated in joblib 0.12 and will be removed in 0.13
  ' removed in 0.13', DeprecationWarning)
/home/justinxu/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py:268: DeprecationWarning: check_pickle is deprecated in joblib 0.12 and will be removed in 0.13
  ' removed in 0.13', DeprecationWarning)


0.8518067547290483
0.7731057134127711
0.9958920620864389
0.8704701089001409
0.5203587511540708
0.005290590586667711
0.645933014354067
0.010495218844748503


In [65]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X_train, y_train)

print 'naive bayes'
# makes predictions
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

train_preds = [pred > 0.5 for pred in train_predictions]
test_preds = [pred > 0.5 for pred in test_predictions]

get_scores(train_preds, y_train, test_preds, y_test)

naive bayes
0.7026664698792217
0.7875139586823003
0.5551127838043933
0.6511996998946746
0.8507621577826767
0.013868751181995839
0.5263157894736842
0.027025366992199498
